spring:
  application:
    name: GraoMestre
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${MYSQL_URL}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}

jwt:
  public:
    key: ${JWT_PUBLIC_KEY}
  private:
    key: ${JWT_PRIVATE_KEY}

image:
  upload:
    dir: ${IMAGE_UPLOAD_DIR:/app/uploads}
  base-path: /images/

app:
  base-url: ${APP_BASE_URL}

server:
  port: ${PORT:8081}

mercadopago:
  access:
    token: ${MP_ACCESS_TOKEN}