spring:
  application:
    name: GraoMestre
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${MYSQL_URL}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}



jwt:
  public:
    key: ${JWT_PUBLIC_KEY}
  private:
    key: ${JWT_PRIVATE_KEY}

image:
  upload:
    dir: ${IMAGE_UPLOAD_DIR:/app/uploads} # Apontando para o seu Volume persistente
  base-path: /images/

app:
  base-url: ${APP_BASE_URL}

server:
  port: ${PORT:8081}

mercadopago:
  access:
    token: ${MP_ACCESS_TOKEN}
  urls:
    webhook: ${MP_WEBHOOK_URL}
    success: ${MP_SUCCESS_URL}
    failure: ${MP_FAILURE_URL}
    pending: ${MP_PENDING_URL}

front:
  base-url: ${FRONT_BASE_URL}