spring:
  application:
    name: GraoMestre
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gm_db?createDatabaseIfNotExist=true 
    username: root
    password: Havan2015@
  mail:
    host: smtp.gmail.com
    port: 587
    username: lucasliaw20@gmail.com
    password: iitw egju pycb vgyc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

jwt:
  public:
    key: classpath:certs/authz.pub
  private:
    key: classpath:certs/authz.pem

image:
  upload:
    dir: src/main/resources/static/images
  base-path: /images/
app:
  base-url: http://192.168.15.88:8081

server:
  port: 8081
  address: 0.0.0.0

mercadopago:
  access:
    token: APP_USR-472750299203932-032216-96b5f9ba975230f25cc4d7c8d4ae9fb2-3284167771
